# Generated by Django 4.2.26 on 2025-11-12 23:22

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(hours=1), help_text='Length of stay'),
            preserve_default=False,
        ),
    ]
