# Generated by Django 4.2.26 on 2025-11-13 20:48

import booking.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=booking.utils.create_id, editable=False, max_length=7, unique=True),
        ),
    ]
