# Generated by Django 4.2.26 on 2025-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
    ]
