# Generated by Django 4.2.26 on 2025-11-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_aprroved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='aprroved',
        ),
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=10),
        ),
    ]
