# Generated by Django 4.2.26 on 2025-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
