# Generated by Django 4.2.26 on 2025-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
    ]
